### ISSUE TITLE
networkStream.pipe is not a function

### ISSUE THREAD

**Issue by SchaJ** [shoutem/cli#144]
New Ubuntu VM

 Attempting to clone uisng shoutem cli and receiving error, 
`networkStream.pipe is not a function`

Node v18.4.0
npm v8.12.1
git v2.25.1
yarn v1.22.19
react-native-cli v2.0.1
shoutem v0.14.2

**Comment by SchaJ** [comment]
`shoutem last-error
stack: 
  """
    TypeError: networkStream.pipe is not a function
        at /usr/lib/node_modules/@shoutem/cli/node_modules/download-cached/index.js:115:19
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at exports.default (/usr/lib/node_modules/@shoutem/cli/src/services/decompress.js:16:19)
        at pullPlatform (/usr/lib/node_modules/@shoutem/cli/src/services/platform.js:25:3)
        at downloadApp (/usr/lib/node_modules/@shoutem/cli/src/services/platform.js:164:3)
        at clone (/usr/lib/node_modules/@shoutem/cli/src/commands/clone.js:193:5)
        at executeAndHandleError (/usr/lib/node_modules/@shoutem/cli/src/services/error-handler.js:77:5)
        at Object.handler (/usr/lib/node_modules/@shoutem/cli/src/cli/clone.js:32:3)
  """
message: networkStream.pipe is not a function
`

**Comment by bassemawny** [comment]
Hello, 

Is there any updates about this issue? I am also facing it and can't seem to find a way around it.

`shoutem last-error` shows me this:

```
➜ Workspace shoutem last-error
stack:
  """
    TypeError: networkStream.pipe is not a function
        at /opt/homebrew/lib/node_modules/@shoutem/cli/node_modules/download-cached/index.js:115:19
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at exports.default (/opt/homebrew/lib/node_modules/@shoutem/cli/src/services/decompress.js:16:19)
        at pullPlatform (/opt/homebrew/lib/node_modules/@shoutem/cli/src/services/platform.js:25:3)
        at downloadApp (/opt/homebrew/lib/node_modules/@shoutem/cli/src/services/platform.js:164:3)
        at clone (/opt/homebrew/lib/node_modules/@shoutem/cli/src/commands/clone.js:193:5)
        at executeAndHandleError (/opt/homebrew/lib/node_modules/@shoutem/cli/src/services/error-handler.js:77:5)
        at Object.handler (/opt/homebrew/lib/node_modules/@shoutem/cli/src/cli/clone.js:32:3)
  """
message: networkStream.pipe is not a function
```

Node v18.4.0
npm v8.12.1
shoutem v0.14.2
react-native-cli v2.0.1

**Comment by bassemawny** [comment]
After some investigation, seems like the issue is solved by switching to node v16.16.0

**Comment by WhereInAnnapolis-Mitch** [comment]
> After some investigation, seems like the issue is solved by switching to node v16.16.0

This worked for me as well, thanks @bassemawny
