### ISSUE TITLE
`npm run configure` failed with code 1

### ISSUE THREAD

**Issue by louisdv** [shoutem/cli#26]
Hello,

I have an issue with "shoutem clone" on Mac (npm 5.4.2, node 8.1.0) : 
```
Creating extensions.js
Running preBuild for all extensions
[running preBuild] - shoutem.application: 1.811ms
[running preBuild] - shoutem.auth: 1.466ms
preBuild: 183.996ms
Starting pods install...
{ Error: spawn pod ENOENT
    at exports._errnoException (util.js:1014:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn pod',
  path: 'pod',
  spawnargs: [ 'install' ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shoutem/platform@1.2.5 configure: `node scripts/configure`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @shoutem/platform@1.2.5 configure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/louis/.npm/_logs/2017-10-02T13_21_23_360Z-debug.log
`npm run configure` failed with code 1

Use `shoutem last-error` for more info
If you think this error is caused by bug in the shoutem command, you can report the issue here: https://github.com/shoutem/cli/issues
```

Thanks for your help.

**Comment by Vladimir-Vdovic** [comment]
Hi @louisdv,

At first glance it seems like an issue with [cocoapods](https://cocoapods.org/). I'd suggest making sure you installed cocoapods on your machine and if you do, update them to make sure they're not at fault for this issue.

**Comment by louisdv** [comment]
Thanks @Vladimir-Vdovic, it is indeed an issue with cocoapods. 
Before my initial message, I updated npm, node, react-native, shoutem and yarn, but not cocoapods...

After an other "sudo gem install cocoapods", the cloning went fine!
Cheers.
