### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by minotaurrr** [shoutem/cli#34]
Hi guys,

I'm getting this error when I run `shoutem clone`

```
? Select your app Restaurants (39905)
cloning to Restaurants
? Directory Restaurants already exists Overwrite
Cloning 'Restaurants' to 'Restaurants'...
unexpected end of file

Use shoutem last-error for more info


errno:   -5
code:    Z_BUF_ERROR
stack: 
  """
    Error: unexpected end of file
        at Zlib.zlibOnError [as onerror] (zlib.js:133:17)
  """
message: unexpected end of file
```

Tried `brew update` but didn't help. Anyone with a similar experience?

**Comment by Vladimir-Vdovic** [comment]
Hi @minotaurrr,

I've tried replicating the issue with your app (I'm an Admin on the Shoutem Builder, so I'm able to do so, other users can't clone other's' apps).

I was unable to reproduce the issue. This may be an issue with npm, check this issue for more information.

My environment:
npm 3.10.10
Node.js 6.11.0
OSX 10.13.1

**Comment by nazrdogan** [comment]
I m getting same error.

**Comment by nazrdogan** [comment]
@minotaurrr  Did you solve your problem ?

**Comment by aiguanglin** [comment]
I m getting same error too.

**Comment by digiwala** [comment]
I m getting same error too.

**Comment by digiwala** [comment]
Please solve this issue

**Comment by ashokkumar88** [comment]
I am getting same error.

**Comment by atulquest93** [comment]
Also getting the same error ! Any solutions ?

**Comment by Vladimir-Vdovic** [comment]
Hey everyone. Can you please provide your environment details so I can attempt to reproduce the issue?

Looking at other people's reports regarding this, the issue is often tied to an unstable or otherwise unusual internet connection. It's possible that proxies, VPNs or simply a poor connection may be causing issues when attempting to download the issue.

Apparently, Nodejs versions 4.6.0 and 7.X.X help resolve the issue in most cases as well.

**Comment by atulquest93** [comment]
@nazrdogan  Which shoutem cli version you are using ?

**Comment by ashokkumar88** [comment]
Mine issue resolved now. I downgraded my node version to 7.x.x and it is working fine now.

**Comment by ashokkumar88** [comment]
@atulquest93 Downgrade your node version to 7.x.x and it will work.

**Comment by nazrdogan** [comment]
@atulquest93  I m using .  0.10.9

**Comment by digiwala** [comment]
node v- 8.9.4  arch -64 bit on windows v- 10 arch -64 bit Pro

**Comment by digiwala** [comment]
also tried node -v  7.10.1 , v 7.2.1, v- 8.9.4 with shoutem-cli v -0.10.9

**Comment by gewentao** [comment]
getting the same error with node v7.10.0, v8.9.4 LTS

**Comment by aiguanglin** [comment]
it don`t work with node v7.10.1,npm v4.2.0 macOS v10.13.2

**Comment by gewentao** [comment]
Still getting this error with: 

```
> npm -v
3.10.10

> node -v
v6.11.0

> shoutem -v
0.10.9
```

Is anyone working on this issue? Thanks!

**Comment by trumhemcut** [comment]
Me too, same issue:
```
> npm -v
5.6.0
> node -v
v8.5.0
> shoutem -v
0.10.9
```

**Comment by aesqe** [comment]
Sorry for the long wait, everyone, I hope we'll be able to fix this soon.

We've released a new beta version on npm - it does not fix the issue, but it should provide clearer HTTP and unzip errors.

Please install it (`npm install -g @shoutem/cli@beta`) and try cloning again. When you get an error, please paste it here again.

Thank you for your patience.

**Comment by aesqe** [comment]
We've published a new beta to npm today (v0.11.0-beta5).

After spending some time reading about zlib errors and trying to replicate this particular error*, we've decided to do the following if a Z_BUF_ERROR is encountered when unpacking tgz archives:
* try to re-download the failing archive once
* throw the error if a re-download has failed as well

There's always the possibility that this is a non-fatal error (https://zlib.net/zlib_faq.html#faq05) and the process might be able to continue, but that's hard to determine without more information. Therefore, we'll look into implementing checksums so we can be certain of a downloaded file's integrity.

\* _the results were inconsistent. We've encountered the error *once* when running shoutem clone, and everything went fine a minute later when retrying the same command. So, it's probably safe to say that the error is somewhere in the network transfer._

**Comment by idev007** [comment]
Node, npm and shoutem version are same in my windows 8 and window 10
But shoutem clone is working in window 10 whereas not in windows 8

**Comment by idev007** [comment]
It is not working on windows 8, 10 but it is working in mac os

**Comment by davinderkumar** [comment]
$uname -a
Darwin Davinders-MBP 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

//MacOS High Sierra; 10.13.2 (17C88)

$ node -v
v10.6.0

$ npm -v
6.1.0

$ shoutem -v
0.11.0-beta5

shoutem last-error
errno:   -5
code:    Z_BUF_ERROR
stack: 
  """
    Error: unexpected end of file
        at Zlib.zlibOnError [as onerror] (zlib.js:153:17)
  """
message: unexpected end of file

If you think this error is caused by bug in the shoutem command, you can report the issue here: https://github.com/shoutem/cli/issues

**Comment by davinderkumar** [comment]
It worked after I deleted .shoutem folder from user home

$rm -rf ~/.shoutem
