### ISSUE TITLE
[error] shoutem clone

### ISSUE THREAD

**Issue by html5cat** [shoutem/cli#39]
Running `shoutem clone` gets me the following error:
```
Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
```
`shoutem last-error`
```
stack: 
  """
    Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
        at Object.exports.decode (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/headers.js:270:43)
        at Extract.onheader (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:120:39)
        at Extract._write (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:243:8)
        at Extract._continue (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:207:28)
        at oncontinue (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:64:10)
        at Extract.ondrain (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:84:5)
        at Extract._write (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:243:8)
        at Extract._continue (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:207:28)
        at oncontinue (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:64:10)
        at onunlock (/usr/local/lib/node_modules/@shoutem/cli/node_modules/tar-stream/extract.js:70:24)
        at Source.stream.on (/usr/local/lib/node_modules/@shoutem/cli/node_modules/decompress-tar/index.js:36:4)
        at emitNone (events.js:110:20)
        at Source.emit (events.js:207:7)
        at endReadableNT (/usr/local/lib/node_modules/@shoutem/cli/node_modules/readable-stream/lib/_stream_readable.js:992:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
  """
message: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

If you think this error is caused by bug in the shoutem command, you can report the issue here: https://github.com/shoutem/cli/issues
```

**Comment by banovotz** [comment]
__________________________________
Please type your reply at the top of the email...

------------------------------------------------------


Shoutem | Jan 06, 2018 12:47AM UTC   

Hello shoutem/cli,
thank you for submitting your request. We have received your request and are working on responding to you as soon as possible. If you have any additional information to add to this case, please reply to this email.


Thanks in advance for your patience and support.


------------------------------------------------------

For your reference this is Case #: 188005

------------------------------------------------------


Support powered by Assistly (http://www.assistly.com/)

[[1454243301d6674cff753b52dc31a3d9c332662b-1116908793]]

**Comment by html5cat** [comment]
clearing `/.shoutem/cache/cached-requests` seems to fix it but now I get the following error:
```
code:         1
message:      `npm run configure` failed with code 1
childProcess: 
  domain:        null
  _events: 
  _eventsCount:  2
  _closesNeeded: 1
  _closesGot:    1
  connected:     false
  signalCode:    null
  exitCode:      1
  killed:        false
  spawnfile:     /bin/sh
  _handle:       null
  spawnargs: 
    - /bin/sh
    - -c
    - npm run configure
  pid:           27742
  stdin:         null
  stdout:        null
  stderr:        null
  stdio: 
    - null
    - null
    - null

```

**Comment by Vladimir-Vdovic** [comment]
[This post](https://github.com/angular/angular-cli/issues/6671#issuecomment-312006083) may offer a way to resolve this. I've been unable to reproduce this with up-to-date versions of npm and Node.js.

If the linked post isn't a solution for you, can you please elaborate on your local environment and possible steps to reproduce so we could investigate this further?

**Comment by Vladimir-Vdovic** [comment]
Closing issue due to inactivity. Prompt for reopen if the issue is still relevant.
