### ISSUE TITLE
`npm run configure` failed with code 1 when trying to clone

### ISSUE THREAD

**Issue by johnpg82** [shoutem/cli#60]
Hello, 

I'm trying to clone my app and I am getting the following in the error log.

code:         1
message:      `npm run configure` failed with code 1
childProcess: 
  domain:        null
  _events: 
  _eventsCount:  2
  _closesNeeded: 1
  _closesGot:    1
  connected:     false
  signalCode:    null
  exitCode:      1
  killed:        false
  spawnfile:     /bin/sh
  _handle:       null
  spawnargs: 
    - /bin/sh
    - -c
    - npm run configure
  pid:           3967
  stdin:         null
  stdout:        null
  stderr:        null
  stdio: 
    - null
    - null
    - null

If you think this error is caused by bug in the shoutem command, you can report the issue here: https://github.com/shoutem/cli/issues

I tried it again as root and got the following.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'configure' ]
2 info using npm@6.9.0
3 info using node@v6.17.1
4 verbose run-script [ 'preconfigure', 'configure', 'postconfigure' ]
5 info lifecycle @shoutem/platform@2.0.0~preconfigure: @shoutem/platform@2.0.0
6 info lifecycle @shoutem/platform@2.0.0~configure: @shoutem/platform@2.0.0
7 verbose lifecycle @shoutem/platform@2.0.0~configure: unsafe-perm in lifecycle true
8 verbose lifecycle @shoutem/platform@2.0.0~configure: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/shoutem/html/SS2/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
9 verbose lifecycle @shoutem/platform@2.0.0~configure: CWD: /home/shoutem/html/SS2
10 silly lifecycle @shoutem/platform@2.0.0~configure: Args: [ '-c', 'node scripts/configure' ]
11 silly lifecycle @shoutem/platform@2.0.0~configure: Returned: code: 1  signal: null
12 info lifecycle @shoutem/platform@2.0.0~configure: Failed to exec configure script
13 verbose stack Error: @shoutem/platform@2.0.0 configure: `node scripts/configure`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid @shoutem/platform@2.0.0
15 verbose cwd /home/shoutem/html/SS2
16 verbose Linux 4.14.109-99.92.amzn2.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "configure"
18 verbose node v6.17.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @shoutem/platform@2.0.0 configure: `node scripts/configure`
22 error Exit status 1
23 error Failed at the @shoutem/platform@2.0.0 configure script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by deucemac** [comment]
Hey @johnpg82, did you ever get this resolved? I've got the same issue right now and it's keeping me from being able to take the proper steps. I've just walking through the steps of the Getting Started Tutorial.  https://shoutem.github.io/docs/extensions/tutorials/getting-started

Any help is appreciated!
