### ISSUE TITLE
can't deploy react app in github

### ISSUE THREAD

**Issue by Tej2407** [shoutem/cli#62]
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [ 'config', 'user.name' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@0.1.0 deploy: `gh-pages -b master -d build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-05-31T06_48_16_615Z-debug.log

**Comment by Rexman17** [comment]
having same issue

**Comment by SystemDZ** [comment]
**Others mentioned here to install Git in order to fix the issue**
[https://github.com/facebook/create-react-app/issues/8243#issuecomment-569149918](url)

**Comment by Rajesh9166** [comment]
having same issue. please confirm how to fix this

**Comment by vedantpatel07756** [comment]
me to having the same problem even i installed git
