### ISSUE TITLE
Error when pulling down a copy of my app

### ISSUE THREAD

**Issue by vstlouis** [shoutem/cli#9]
```
{
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "extensions.beta.shoutem.com",
  "host": "extensions.beta.shoutem.com",
  "port": 443,
  "stack": "Error: getaddrinfo ENOTFOUND extensions.beta.shoutem.com extensions.beta.shoutem.com:443\n    at errnoException (dns.js:28:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)",
  "message": "getaddrinfo ENOTFOUND extensions.beta.shoutem.com extensions.beta.shoutem.com:443"
}
```

**Comment by Vladimir-Vdovic** [comment]
Looking at the issue online I found [this](https://stackoverflow.com/questions/23259697/error-getaddrinfo-enotfound-in-nodejs-for-get-call).

However this shouldn't be happening at any rate, so I will label this as a bug. Let us know if there's any update to the situation so we can move towards resolving this issue.

**Comment by Vladimir-Vdovic** [comment]
Closing due to inactivity. Prompt for reopen if issue is still relevant.
